### ISSUE TITLE
Not possible to establish connection

### ISSUE THREAD

**Issue by PieElecAm** [GouveaHeitor/nipe#24] opened 2018-06-23 22:07 UTC
Hi,

I'm receiving same error on TurnKey-Linux-Jessie

I've successfully gotten this tool to run on 3 different machines, just this one doesn't want to work. I've installed also 
"apt-get install perlbrew - && curl -L http://xrl.us/installperlnix | bash"

And it's still not running.

When I run any perl nipe.pl command it gives no output, and when I run: perl nipe.pl status it shows "[!] ERROR: sorry, it was not possible to establish a connection to the server."

**Comment by hackison** [comment] 2018-08-03 09:08
hello im also getting the same problem

**Comment by saptarshimondal** [comment] 2018-08-07 13:04
I am also getting same error.

**Comment by GouveaHeitor** [comment] 2018-08-14 00:52
Did you run the command "perl nipe.pl install"? Did any errors occur during the installation?!

@hackison  and @saptarshimondal What are your linux distributions?

**Comment by hackison** [comment] 2018-08-14 03:26
No @GouveaHeitor no error came during installation the error happened while running the tool Perl nipe.perl start when i try to start the service this error occurs and I'm using kali linux 2018.2

**Comment by lsiddarth** [comment] 2018-09-22 04:41
Same issue here with me 
Linux  4.18.0-kali1-amd64 #1 SMP Debian 4.18.6-1kali1 (2018-09-10) x86_64 GNU/Linu

**Comment by GouveaHeitor** [comment] 2019-03-25 23:49
Hi @PieElecAm, @hackison, @saptarshimondal, @XXJanusXX and @lhulhumaung 

I recently made some updates on Nipe ... Could any of you guys confirm that everything works in the new version?

Thx!!

**Comment by anomydarklord** [comment] 2019-05-28 16:50
@GouveaHeitor Please fix this Problem
[!] ERROR: sorry, it was not possible to establish a connection to the server.
1) Operating System:- Linux 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-2kali1 (2019-05-15) x86_64 GNU/Linux (Kali 2019.2 latest)
2)Perl:-perl 5, version 28, subversion 1 (v5.28.1) built for x86_64-linux-gnu-thread-multi
3)Iptables:- iptables v1.8.2
4)Tor:-Tor version 0.3.5.8
and
Switch is up to date (2.17).
JSON is up to date (4.02).
LWP::UserAgent is up to date (6.39).

its working fine 1 month ago . but now i check its not working.
this Error will show when we type "perl nipe.pl status"
i try 
to edit /lib/Nipe/ Start.pm file
system ("sudo systemctl start tor");
or 
edit Fuction.pm file too
systemctl tor restart something like that 

But still NOT WORKING.......................

**Comment by alshawwa** [comment] 2019-05-28 21:04
everything seems to be working fine for me on kali.
 
download a fresh copy of nipe and before running the install do the following.
apt install  libjson-perl   libswitch-perl  libtest-lwp-useragent-perl 
then go to the newly downloaded nipe folder and do 
perl nipe.pl install 
when installation is try your nipe.

**Comment by anomydarklord** [comment] 2019-05-29 03:22
> everything seems to be working fine for me on kali.
> 
> download a fresh copy of nipe and before running the install do the following.
> apt install libjson-perl libswitch-perl libtest-lwp-useragent-perl
> then go to the newly downloaded nipe folder and do
> perl nipe.pl install
> when installation is try your nipe.

thanks for reply
i tried
apt reinstall libjson-perl libswitch-perl libtest-lwp-useragent-perl
perl nipe.pl install
 still facing same error
i think this error come because of miss match version of iptables 
i see people using iptables v1.6
i am using iptables v1.8.2

Hope @GouveaHeitor  Soon Fix this Error Soon
also i read many other people cmd facing this issue

**Comment by alshawwa** [comment] 2019-05-29 14:10
> > everything seems to be working fine for me on kali.
> > download a fresh copy of nipe and before running the install do the following.
> > apt install libjson-perl libswitch-perl libtest-lwp-useragent-perl
> > then go to the newly downloaded nipe folder and do
> > perl nipe.pl install
> > when installation is try your nipe.
> 
> thanks for reply
> i tried
> apt reinstall libjson-perl libswitch-perl libtest-lwp-useragent-perl
> perl nipe.pl install
> still facing same error
> i think this error come because of miss match version of iptables
> i see people using iptables v1.6
> i am using iptables v1.8.2
> 
> Hope @GouveaHeitor Soon Fix this Error Soon
> also i read many other people comment facing this issue

i am running SMP Debian 4.19.37-2kali1 (2019-05-15) x86_64 GNU/Linux &&  iptables 1.8.2-4 and it is running fine. i suspect the issue is with tor it self . just for curiosity  in a shell run tor and see if it actually launches and connects.

**Comment by anomydarklord** [comment] 2019-05-30 14:37
> > > everything seems to be working fine for me on kali.
> > > download a fresh copy of nipe and before running the install do the following.
> > > apt install libjson-perl libswitch-perl libtest-lwp-useragent-perl
> > > then go to the newly downloaded nipe folder and do
> > > perl nipe.pl install
> > > when installation is try your nipe.
> > 
> > 
> > thanks for reply
> > i tried
> > apt reinstall libjson-perl libswitch-perl libtest-lwp-useragent-perl
> > perl nipe.pl install
> > still facing same error
> > i think this error come because of miss match version of iptables
> > i see people using iptables v1.6
> > i am using iptables v1.8.2
> > Hope @GouveaHeitor Soon Fix this Error Soon
> > also i read many other people comment facing this issue
> 
> i am running SMP Debian 4.19.37-2kali1 (2019-05-15) x86_64 GNU/Linux && iptables 1.8.2-4 and it is running fine. i suspect the issue is with tor it self . just for curiosity in a shell run tor and see if it actually launches and connects.

Thanks for Support
Same version I also use of both
at the End. I am very much sure this Error come due to 
cleaning my memory
by using these app Stacer & Bleachbit 
or running these command
apt clean && apt autoclean
apt autoremove to remove previous version of apps in the upgradable seasions
i also try apt reinstall tor 
still not working... 
hope soon i found a way to solve this
but now i am using anonsurf

**Comment by anomydarklord** [comment] 2019-05-30 14:47
> > > > everything seems to be working fine for me on kali.
> > > > download a fresh copy of nipe and before running the install do the following.
> > > > apt install libjson-perl libswitch-perl libtest-lwp-useragent-perl
> > > > then go to the newly downloaded nipe folder and do
> > > > perl nipe.pl install
> > > > when installation is try your nipe.
> > > 
> > > 
> > > thanks for reply
> > > i tried
> > > apt reinstall libjson-perl libswitch-perl libtest-lwp-useragent-perl
> > > perl nipe.pl install
> > > still facing same error
> > > i think this error come because of miss match version of iptables
> > > i see people using iptables v1.6
> > > i am using iptables v1.8.2
> > > Hope @GouveaHeitor Soon Fix this Error Soon
> > > also i read many other people comment facing this issue
> > 
> > 
> > i am running SMP Debian 4.19.37-2kali1 (2019-05-15) x86_64 GNU/Linux && iptables 1.8.2-4 and it is running fine. i suspect the issue is with tor it self . just for curiosity in a shell run tor and see if it actually launches and connects.
> 
> Thanks for Support
> Same version I also use of both
> at the End. I am very much sure this Error come due to
> cleaning my memory
> by using these app Stacer & Bleachbit
> or running these command
> apt clean && apt autoclean
> apt autoremove to remove previous version of apps in the upgradable seasions
> i also try apt reinstall tor
> still not working...
> hope soon i found a way to solve this
> but now i am using anonsurf

Yeahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

Finally Solve it BROOOooooooooooooooooooooooooooooooooooooooo
Thankssssssssss you tooo alsooooooooooooooooooooooooooooooooooooooooo

**Comment by anomydarklord** [comment] 2019-05-30 14:58
Friends I Recently Find the Solution of This 
Do it My way
apt reinstall tor
remove the nipe directory where you save nipe ( rm -r nipe)
then
git clone https://github.com/GouveaHeitor/nipe.git
then
{optional} apt reinstall libjson-perl libswitch-perl libtest-lwp-useragent-perl
if needed reinstall iptables too
then
cpan install Switch JSON LWP::UserAgent
thats its
use it by perl perl nipe.pl start 
check status perl nipe.pl status
Hola you done it
Note: use of Stacer and bleachbit cause this Errror
so use by own knowledge which memory can be deleted

**Comment by anomydarklord** [comment] 2019-05-30 15:05
> No @GouveaHeitor no error came during installation the error happened while running the tool Perl nipe.perl start when i try to start the service this error occurs and I'm using kali linux 2018.2

Friends I Recently Find the Solution of This 
Do it My way
apt reinstall tor
remove the nipe directory where you save nipe ( rm -r nipe)
then
git clone https://github.com/GouveaHeitor/nipe.git
then
{optional} apt reinstall libjson-perl libswitch-perl libtest-lwp-useragent-perl
if needed reinstall iptables too
then
cpan install Switch JSON LWP::UserAgent
thats its
use it by perl perl nipe.pl start 
check status perl nipe.pl status
Hola you done it
Note: use of Stacer and bleachbit cause this Errror
so use by own knowledge which memory can be deleted
#anomydarklord

**Comment by GouveaHeitor** [comment] 2019-07-22 15:26
Hi Guys,

I think I got this error fixed, can someone please confirm it?

Thx.

**Comment by GouveaHeitor** [comment] 2019-09-22 18:55
Hi guys,

I need an answer on this subject...
Should no-one comment on it, I will assume that this has been resolved.

Thx

**Comment by Iamgoupil** [comment] 2019-10-01 23:41
hi ! I did that and it works for me...

# Reinstall nipe on ubuntu 19.10 after fail
 
  remove /home/XXyournameXX/.cpanm

$sudo apt-get install perlbrew - && curl -L http://xrl.us/installperlnix | bash

$sudo apt reinstall tor

$sudo rm -r nipe

$git clone https://github.com/GouveaHeitor/nipe.git

$sudo apt reinstall libjson-perl libswitch-perl libtest-lwp-useragent-perl


$sudo apt reinstall iptables


$cpan install Switch JSON LWP::UserAgent

$cd nipe

$sudo chmod +x setup.sh

$./setup.sh

$perl nipe.pl start   ok
$perl nipe.pl stop    ok
$perl nipe.pl status  $[!] ERROR: sorry, it was not possible to establish a connection to the server.

Gnome extension :Public IP by rostegg  change ip:ok
and test on sites like my-ip.com  all ok
 the  install command and status command don't work for me

**Comment by GouveaHeitor** [comment] 2019-12-05 21:25
Can anyone confirm that the latest updates solved this problem?
I did several tests using Ubuntu, Kali Linux, and Debian and had no problems...

**Comment by TheCyberTecky** [comment] 2019-12-24 00:06
> 
> 
> Can anyone confirm that the latest updates solved this problem?
> I did several tests using Ubuntu, Kali Linux, and Debian and had no problems...

Greetings from Colorado Springs, Colorado USA!  First and foremost, thank you for your 'nipe' development work that you've done for the community.  I will attempt to work with you and other members on this Github page to resolve what appears to be an ongoing issue with the cpan switch process.  My guess is that it may have to deal with iptables?

Device with 'nipe' installed is a Raspberry Pi 3B+
Linux ###### 4.19.81-Re4son-v8+ #1 SMP PREEMPT Wed Nov 6 03:33:03 UTC 2019 aarch64 GNU/Linux

What I've done to resolve seems like what everyone else has attempted on this particular issue.  I would agree with the others who reported previously that the switch process seems to hang after running the "perl nipe.pl start" command, and the only option I have is to execute the "control+c" command a few times to get out of the hang and back to the terminal prompt.  I did see some errors printed on my screen as a result which may help aid your troubleshooting/developing process:

**----------------------------------------- Exerpt of Errors Below -----------------------------------**
chad@J-KALIPI:~/GitHub/nipe$ perl nipe.pl start
[sudo] password for chad:
^Ciptables v1.8.3 (nf_tables): Couldn't load match `state':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.3 (nf_tables): Couldn't load match `owner':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.3 (nf_tables): unknown option "--dport"
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.3 (nf_tables): unknown option "--dport"
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.3 (nf_tables): unknown option "--to-ports"
Try `iptables -h' or 'iptables --help' for more information.
iptables: Operation not supported.
iptables: Operation not supported.
iptables: Operation not supported.
iptables: Operation not supported.
iptables v1.8.3 (nf_tables): unknown option "--to-ports"
Try `iptables -h' or 'iptables --help' for more information.

**Comment by bmeneguele** [comment] 2020-01-25 13:44
@TheCyberTecky, is this issue the same you described in issue #76 ?

First, thanks for the error information you pasted about iptables, this issue is most likely to be an issue with either torrc configuration file and/or /etc/os-release file that doesn't have the `ID_LIKE=` key. What happens is that nipe don't map a default value for configuration options it must have, so in case one of the files I said (tor config or /etc/os-release) lacks any of the information nipe fails silently, carrying empty/undefined variables around, which may get being used during `iptables` rules setup. What is even worse is that some of the commands issued by `iptables` will still work, but may block output data.

The good news is that this issue may get solved by the PR I opened yesterday (PR #87) enabling custom configurations, thus if, for some reason, a config file doesn't have some of the required values, default values are used.

**Comment by TheCyberTecky** [comment] 2020-01-25 15:31
*   @TheCyberTecky<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTheCyberTecky&data=02%7C01%7C%7Cf4ffedf6250e41b99ffd08d7a19cafdc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637155566640031790&sdata=ujF5Pt1GRURWHEGxWy%2BPFiJc2qwiBvWtk7TnzDVJBBM%3D&reserved=0>, is this issue the same you described in issue #76<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGouveaHeitor%2Fnipe%2Fissues%2F76&data=02%7C01%7C%7Cf4ffedf6250e41b99ffd08d7a19cafdc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637155566640041794&sdata=rqI14tvoaQuy0j33AoAJ69FSlLE0RY6U6bFbngxya3A%3D&reserved=0> ?

Correct.


  *   This issue is most likely to be an issue with either torrc configuration file and/or /etc/os-release file that doesn't have the ID_LIKE= key.

Looks like you are addressing this but wanted to share what my config files showed with a simple ‘cat’ command.  The ‘os-release’ had data but ‘torrc’ was NOT found, suggestions?



COMMAND: /etc/os-release

PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2020.1"
VERSION_ID="2020.1"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL=https://bugs.kali.org/

        COMMAND: cat /etc/torrc   <-- NOT FOUND


  *   The good news is that this issue may get solved by the PR I opened yesterday (PR #87<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGouveaHeitor%2Fnipe%2Fpull%2F87&data=02%7C01%7C%7Cf4ffedf6250e41b99ffd08d7a19cafdc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637155566640041794&sdata=cHITYJxc3B8N0NjnS9uqYqvUWxS8ugejJSUXJbCM4jE%3D&reserved=0>) enabling custom configurations, thus if, for some reason, a config file doesn't have some of the required values, default values are used.

Based on the information from my configuration files, would (PR #87) resolve my issue or do I need to install some sort of ‘torrc’ support since I couldn’t find any configuration files on it?

Thanks!

Chad

**Comment by bmeneguele** [comment] 2020-01-25 21:14
@TheCyberTecky , your reply was sent from email? It really broke your links! If possible, send the reply using github interface :P.

About the "tor config file not found" actually the correct path for default tor config file is "/etc/tor/torrc", try to `cat` it. If it's there, please send its content.

Now, about if this issue related to #76... quite, but not entirely: the portion that people stated about
`[!] ERROR: sorry, it was not possible to establish a connection to the server.`
yes, but the other portion of `./nipe.pl start` hanging and forcing the user to hit "ctrl+c", no.

The PR #87 should solve the hanging issue without any additional installation or configuration steps.

```
$ ./nipe.pl install -f
$ ./nipe.pl start
```

will be enough.

**Comment by Ascensao** [comment] 2020-02-26 16:39
not working in my  Kali 2020.1. Anyone managed to make it work?

**Comment by alshawwa** [comment] 2020-02-26 16:45
seems to be working fine on kali 2020.1 i just tried it . are you getting any errors ?

**Comment by bmeneguele** [comment] 2020-02-26 17:20
> not working in my Kali 2020.1. Anyone managed to make it work?

Take a look on issue #88, where I suggest a dummy solution with `# iptables -F`.

**Comment by Ascensao** [comment] 2020-02-27 17:06
@alshawwa  @bmeneguele 

not working. I have done it exactly as readme.md says 👍 
# Download
  $ git clone https://github.com/GouveaHeitor/nipe
  $ cd nipe
    
  # Install libs and dependencies
  $ sudo cpan install Switch JSON LWP::UserAgent Config::Simple
  $ perl nipe.pl install

and I have written iptables -F before nipe.pl start.

``kali@kali:~/nipe$ perl nipe.pl install
Reading package lists... Done
Building dependency tree      
Reading state information... Done
The following additional packages will be installed:
  libip4tc2 libip6tc2 libxtables12 tor-geoipdb torsocks
Suggested packages:
  firewalld mixmaster torbrowser-launcher tor-arm apparmor-utils obfs4proxy
Recommended packages:
  nftables
The following NEW packages will be installed:
  tor tor-geoipdb torsocks
The following packages will be upgraded:
  iptables libip4tc2 libip6tc2 libxtables12
4 upgraded, 3 newly installed, 0 to remove and 552 not upgraded.
Need to get 4,175 kB of archives.
After this operation, 14.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://kali.download/kali kali-rolling/main i386 iptables i386 1.8.4-3 [432 kB]
Get:2 http://kali.download/kali kali-rolling/main i386 libxtables12 i386 1.8.4-3 [81.2 kB]
Get:3 http://kali.download/kali kali-rolling/main i386 libip4tc2 i386 1.8.4-3 [69.9 kB]
Get:4 http://kali.download/kali kali-rolling/main i386 libip6tc2 i386 1.8.4-3 [70.4 kB]
Get:5 http://kali.download/kali kali-rolling/main i386 tor i386 0.4.2.6-1 [1,978 kB]
Get:6 http://kali.download/kali kali-rolling/main i386 tor-geoipdb all 0.4.2.6-1 [1,468 kB]
Get:7 http://kali.download/kali kali-rolling/main i386 torsocks i386 2.3.0-2 [75.5 kB]
Fetched 4,175 kB in 2s (1,754 kB/s)
Reading changelogs... Done
(Reading database ... 277043 files and directories currently installed.)
Preparing to unpack .../0-iptables_1.8.4-3_i386.deb ...
Unpacking iptables (1.8.4-3) over (1.8.3-2) ...
Preparing to unpack .../1-libxtables12_1.8.4-3_i386.deb ...
Unpacking libxtables12:i386 (1.8.4-3) over (1.8.3-2) ...
Preparing to unpack .../2-libip4tc2_1.8.4-3_i386.deb ...
Unpacking libip4tc2:i386 (1.8.4-3) over (1.8.3-2) ...
Preparing to unpack .../3-libip6tc2_1.8.4-3_i386.deb ...
Unpacking libip6tc2:i386 (1.8.4-3) over (1.8.3-2) ...
Selecting previously unselected package tor.
Preparing to unpack .../4-tor_0.4.2.6-1_i386.deb ...
Unpacking tor (0.4.2.6-1) ...
Selecting previously unselected package tor-geoipdb.
Preparing to unpack .../5-tor-geoipdb_0.4.2.6-1_all.deb ...
Unpacking tor-geoipdb (0.4.2.6-1) ...
Selecting previously unselected package torsocks.
Preparing to unpack .../6-torsocks_2.3.0-2_i386.deb ...
Unpacking torsocks (2.3.0-2) ...
Setting up libip4tc2:i386 (1.8.4-3) ...
Setting up libip6tc2:i386 (1.8.4-3) ...
Setting up libxtables12:i386 (1.8.4-3) ...
Setting up tor (0.4.2.6-1) ...
Something or somebody made /var/lib/tor disappear.
Creating one for you again.
Something or somebody made /var/log/tor disappear.
Creating one for you again.
update-rc.d: We have no instructions for the tor init script.
update-rc.d: It looks like a network service, we disable it.
Setting up torsocks (2.3.0-2) ...
Setting up iptables (1.8.4-3) ...
Setting up tor-geoipdb (0.4.2.6-1) ...
Processing triggers for libc-bin (2.29-3) ...
Processing triggers for systemd (244-3) ...
Processing triggers for man-db (2.9.0-2) ...
Processing triggers for kali-menu (2020.1.7) ...
kali@kali:~/nipe$ perl nipe.pl start
kali@kali:~/nipe$ perl nipe.pl status

[!] ERROR: sorry, it was not possible to establish a connection to the server.

kali@kali:~/nipe$ perl nipe.pl stop
kali@kali:~/nipe$ sudo iptables -F
kali@kali:~/nipe$ perl nipe.pl start
kali@kali:~/nipe$ perl nipe.pl status

[!] ERROR: sorry, it was not possible to establish a connection to the server.

kali@kali:~/nipe$ perl nipe.pl stop
kali@kali:~/nipe$ perl nipe.pl start
kali@kali:~/nipe$ curl https://check.torproject.org/api/ip
curl: (6) Could not resolve host: check.torproject.org``

**Comment by alshawwa** [comment] 2020-02-27 17:18
i am not a big fan of cpan , always had issue with cpan in regard to almost every issue everyone is facing here  .  so on my setups i always use the packages that are available in the distro repository. 

give this a try

apt remove tor --purge      " to remove tor and its config files"

then do 

apt install libjson-perl libswitch-perl libconfig-simple-perl libtest-lwp-useragent-perl

then reboot 

when you get back up  run perl nipe.pl install

then run perl nipe.pl start

wait for a few seconds then run perl nipe.pl status   ** sometimes it may take up to a minute **

**Comment by Ascensao** [comment] 2020-02-28 00:27
After following your steps @alshawwa still not working. But maybe I know the reason. I´m using a 32bits Pc with USB boot persistence. 

I changed to 64bit PC on a Virtual Machine and is working fine. Thanks anyway.

**Comment by th3unkn0n** [comment] 2020-04-22 13:40
this worked for me
if you using anything like Stacer it will remove some configs

$ apt 
$ apt reinstall  libjson-perl libswitch-perl libconfig-simple-perl libtest-lwp-useragent-perl

reboot system
$ perl nipe.pl install
$ perl nipe.pl start 
$ curl ifconfig.me

awsome script love it 👌

**Comment by GouveaHeitor** [comment] 2020-04-28 10:25
Hi guys!

Can you try to test Nipe again? I think this is resolved with the most recent commit.

Thx

**Comment by r0m305** [comment] 2020-05-17 09:18
Hey, since i installed nipe, i've been getting this error anytime i need to run tor service manually:
May 17 12:16:07.947 [notice] Tor 0.4.2.6 running on Linux with Libevent 2.1.11-stable, OpenSSL 1.1.1d, Zlib 1.2.11, Liblzma 5.2.4, and Libzstd 1.4.4.
May 17 12:16:07.947 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
May 17 12:16:07.947 [notice] Read configuration file "/etc/tor/torrc".
May 17 12:16:07.951 [warn] Skipping obsolete configuration option "TransListenAddress".
May 17 12:16:07.951 [warn] Skipping obsolete configuration option "DNSListenAddress".
May 17 12:16:07.961 [notice] Opening Socks listener on 127.0.0.1:9050
May 17 12:16:07.961 [warn] Could not bind to 127.0.0.1:9050: Address already in use. Is Tor already running?
May 17 12:16:07.961 [notice] Opening DNS listener on 127.0.0.1:9061
May 17 12:16:07.961 [notice] Opened DNS listener on 127.0.0.1:9061
May 17 12:16:07.961 [notice] Opening Transparent pf/netfilter listener on 127.0.0.1:9051
May 17 12:16:07.961 [warn] Could not bind to 127.0.0.1:9051: Address already in use. Is Tor already running?
May 17 12:16:07.961 [notice] Closing partially-constructed DNS listener on 127.0.0.1:9061
May 17 12:16:07.961 [warn] Failed to parse/validate config: Failed to bind one of the listener ports.
May 17 12:16:07.961 [err] Reading config failed--see warnings above.

**Comment by GouveaHeitor** [comment] 2020-05-27 13:11
All issues here are resolved in the last commit. 
Thx guys!

**Closed** 2020-05-27 13:12 UTC
Labels: bug, help wanted
