### ISSUE TITLE
Workaround for RPi install/error involving cpan (yaml)

### ISSUE THREAD

**Issue by TheCyberTecky** [GouveaHeitor/nipe#76] opened 2019-12-18 13:58 UTC
Raspberry Pi 3B+ (RPi) Arm64, running Kali Arm 2019.4 doesn't seem to work well with the cspan switch portion of the nipe install.  Currently re-installing my RPi with Kali Arm 2019.3a which I believe worked well with nipe install before.  I'll provide a progress update as soon as I complete that process.  Nipe is such a great package, I'd hate to loose that particular functionality so it's worth the effort to troubleshoot for sure!

~ Chad

**Comment by GouveaHeitor** [comment] 2020-01-14 08:56
@TheCyberTecky Any update about this?

**Comment by TheCyberTecky** [comment] 2020-01-24 07:01
Follow-up on RPI 3B+ regarding my attempt to resolve install issue and script start issue was unsuccessful.  I've tried several configuration method attempts such as:

a. Install/configure nipe on RPI 3B+ using a less resource demanding perl switch - Nipe FAILED.
b. Attempted fresh install of Linux OS followed by install/configure - Status: FAILED.
c. Installed swap file using 'dphys-swapfile' to provide 2048 swap size to the RPI 3B+ - Status: FAILED.
d. Completed recommended steps listed on Nipe (Github) forum - Status: FAILED.

Overall, my assessment seems to point the issue to resource exhaustion on the RPI 3B+ during Nipe install of Perl switch portion of the installation instructions.  Problem possibly attributed to recent Perl switch install size and resource demand increase from developers.

Solution: My availability to help troubleshoot and test development changes to your Nipe script and/or willing to provide secure remote access to the RPI 3B+ if that would help?  I'm an avid user/supporter of the NIPE script for about 2 years now and it seems to work fine in virtualbox linux environments, WIndows 10 Pro (WSL2), but I prefer doing my development and pentesting work from the RPI itself.  The current device is the RPI 3B+ but I'm considering the option to purchase the new RPI 4 which has more resources, however, I would like to see the RPI 3B+ be supported by Nipe as well.  

Looking forward to helping where I can!

Chad

**Comment by bmeneguele** [comment] 2020-01-25 11:00
Hi @ , that seems to be an interesting case, but we need some more information before we can tackle the possible issue, could you provide these:

- did you mean the issue happened during `./nipe.pl install` command while processing its `switch statements` or during `Perl::Switch` module installation on the system? 
- what happens to the system when the issue happens? Did you receive any error/warning message in the console? Or your system just hangs? Or you lose connection?
- when you start nipe you're accessing your RPi via SSH or serial console? If you're using solely SSH could you switch to serial and check system log (`dmesg`) and journal log (`journalctl -xe`) ?

I know RPi is resource limited compared to any PC, but it shouldn't get to be point of "exhaustion" running Nipe, that's why I'm asking these additional question to make sure we don't forget any other condition or possible cause in the middle.

Thank you very much!

**Comment by TheCyberTecky** [comment] 2020-01-25 14:23
Hi Bruno,

I appreciate the quick response and your help on the RPI issue and look forward to helping where I can on getting Nipe to install/configure successfully on the RPI.  I will do my best to answer your (3) questions:


  1.  did you mean the issue happened during ./nipe.pl install command while processing its switch statements or during Perl::Switch module installation on the system?

ANSWER: The errors occurred during the “Perl::Switch” installation and the ‘#Install libs and dependencies’ step using the terminal command: “sudo cpan install Switch JSON LWP::UserAgent Config::Simple”.  See details on question 2 below…

  2.  what happens to the system when the issue happens? Did you receive any error/warning message in the console? Or your system just hangs? Or you lose connection?

ANSWER: There are (2) errors that I noticed.  Error #1 I can’t seem to duplicate anymore but could still be an issue.

Error #1 - The first error occurred at the “Perl::Switch” of your Nipe installation instructions.  This was were I originally received a resource timeout error which prompted me to create a larger swap file size.
Error #2 - The second error occurred after executing the “sudo perl nipe.pl start” command from terminal and initially the terminal froze, then I executed the “ctrl+c” command from terminal to quit the process.  I forgot to mention that there was an iptables issue that I previously reported in a separate post on your GitHub page, link here:

https://github.com/GouveaHeitor/nipe/issues/24#issuecomment-568610486
Note – Last year I was successful at installing/operating Nipe on my RPI 3B+, the only difference is that the previous system configuration prior to Nipe install has PIA VPN installed and fully operational.  Now that I think about it I wonder if the ‘PIA VPN’ install (configuration) updated the iptables somehow?  Might be worth my time to at least attempt the same configuration again?
I’m sure I haven’t answered all of your inquiries as of yet but I can at least confirm that I am using SSH to access the RPI terminal and will attempt to complete the ‘dmesg’ and ‘journalctl -xe’ logs via serial – most likely via network (minicom) access.  In the meantime, I’m thinking the main problem might be related with iptables and might be worth looking into?
Thanks,
Chad

**Comment by bmeneguele** [comment] 2020-01-25 21:52
Hmmm ok. Well.. lets keep discussing error number 2 at issue #24 and lets focus about error number 1 in this issue here.

@GouveaHeitor is planning to use other module to actually handle command line parameters, instead of using a switch-case statement, so I think we can do that earlier than planned to get rid of this issue, for sure. But at the same time, I think the information you can gather to us will help to limit ourselves in future changes of the code during decision making about which module should be used, or not, for certain tasks.

I'm going to give you some steps that I would like to see the output/results, if you don't mind of course:
- you can use your ssh connection normally, don't worry about connecting via serial;
- run `./nipe.pl start` and wait for certain time to make sure it's indeed stuck and let it running, don't press ctrl+c to interrupt that;
- open a new ssh connection, and run: `dmesg`, saving its output to a file that you could copy to your local machine;
- also run `free` and save its output to a file to give us a notion of memory usage of the whole system;
- and finally `ps aux | grep -e cpanm -e perl` (I'm not sure how you're installing perl modules (cpan, cpanm, ...)

Grab all this data and paste at gist.github.com and then copy+paste the link of the generated gist here to us.

One workaround you could try is to install Perl::Switch module from system's repository instead of metacpan:

`# apt install libswitch-perl`

**Comment by TheCyberTecky** [comment] 2020-01-26 02:37
I’m still a bit new at using Github (from a developer perspective) but I’ll do my best to provide feedback on your questions.  Please forgive me if I end up providing too much detail but in this case I’m sure you could use all data I see on my end.  NOTE – Noticed new error generated after re-installing Nipe that I believe is associated with one of the developer fixes that are being worked on by PR?

ERROR: “[!] ERROR: sorry, it was not possible to establish a connection to the server.”

Listed below are my responses to your feedback -

  *   you can use your ssh connection normally, don't worry about connecting via serial;
[RESPONSE] Ok.  I’ll continue using SSH for the remainder of this project.
  *   run ./nipe.pl start and wait for certain time to make sure it's indeed stuck and let it running, don't press ctrl+c to interrupt that;
  *   open a new ssh connection, and run: dmesg, saving its output to a file that you could copy to your local machine;
  *   also run free and save its output to a file to give us a notion of memory usage of the whole system;
[RESPONSE] I’ll do better than that and provide you with ‘free’ and ‘dmesg’ of both cpan install perl::switch AND ./nipe.pl steps in the following gist.github.com links:

a) cpan install perl::switch (DMESG)
   https://gist.github.com/TheCyberTecky/8c093c923a622cee6a891cd347e96677#file-cpan-install-perl-switch-dmesg-rtf
b) cpan install perl::switch (LIVE INSTALL RECORD)
   https://gist.github.com/TheCyberTecky/25876fc7c0fd7c4747fdfe091825986a#file-nipe-cpan-install-switch-json-live-output-rtf

c) ./nipe.pl install (FREE+DMESG)
   https://gist.github.com/TheCyberTecky/9090637a71a5562dab97b47a1b9d2ef5#file-nipe-pl-install-dmesg-rtf

d) ./nipe.pl start (DMESG)
   https://gist.github.com/TheCyberTecky/87465d9ee93b474f90402d234ce14665#file-nipe-pl-status-start-dmesg-rtf

  *   and finally ps aux | grep -e cpanm -e perl (I'm not sure how you're installing perl modules (cpan, cpanm, ...)
[RESPONSE] root@J-KALIPI:/home/chad# ps aux | grep -e cpanm -e perl
root      814037  0.0  0.0   2804   680 pts/1    S+   01:57   0:00 grep -e cpanm -e perl

  *   One workaround you could try is to install Perl::Switch module from system's repository instead of metacpan:
  *   # apt install libswitch-perl
[RESPONSE] Alternate Nipe install method appeared to install OK but same issue with script hanging after executing ./nipe.pl start
https://gist.github.com/TheCyberTecky/3d6ccc68e6837ba5b9eec396e2f03ed8#file-nipe-pl-install-libswitch-perl-status-start-dmesg-rtf

**Comment by bmeneguele** [comment] 2020-01-29 19:13
@TheCyberTecky unfortunately I couldn't notice anything wrong during Perl::Switch install :/ but we're going to remove its dependency from the code anyway, just not sure when, but hopefully soon.

I'm going to keep this issue open while the total drop of Perl::Switch doesn't happen.

**Comment by dvinciguerra** [comment] 2020-02-20 12:26
We dont need Switch module to dispatch sub commands...

See my example:

```perl
#!/usr/bin/env perl

use v5.10;
use feature qw/say/;

package Nipe::Commands;

my $COMMANDS = {
  install => "Nipe::Commands::Install",
  restart => "Nipe::Commands::Restart",
  start   => "Nipe::Commands::Start",
  status  => "Nipe::Commands::Status",
  stop    => "Nipe::Commands::Stop",
};

sub run {
  my ($self, $argv) = @_;

  my $subcommand = $argv->[0];
  my $command_class = $COMMANDS->{$subcommand};

  unless ($command_class) {
    say "Nipe::Commands::Help";
    exit
  }

  say $command_class; # $command_class->new(...)
  exit
}


package main;

Nipe::Commands->run(\@ARGV);
```

**Comment by bmeneguele** [comment] 2020-02-20 13:23
@dvinciguerra that's actually a good suggestion, but at the same time it would need a way to handle command options (-c, -f, ...). Take a look on the current state of "develop" branch, that's where the most recent changes goes until the maintainer merge it to "master" branch, there you'll see that some commands already have different options supported.

@GouveaHeitor was already planning to change Perl::Switch module to Getopt::* (Std and Long probably) that are core modules to handle short and long options. Feel free to check "develop" branch and possibly submit a pull request, thus we can review the code through there.

**Comment by dvinciguerra** [comment] 2020-02-20 15:47
Yep,
About sub commands options... it's possible delegating to each sub command to configure/parse their own options using Getopt::Long as you commented.

Something like this example:

```perl
package Nipe::Commands::Start;
use strict;
use warnings;

use Getopt::Long qw(GetOptionsFromArray);

sub run {
  my ($self, $arguments) = @_;

  my $options = _parse_arguments($arguments);

  use Data::Dumper; print Dumper($options);

  print $self;
}

sub _parse_arguments {
  my ($arguments) = @_;

  my $options = {
    config => '',
    force => 0,
  };

  GetOptionsFromArray(
    $arguments,
    "config=s" => \$options->{config},
    "force" => \$options->{force},
  );

  return $options;
}

1;
```

I'm writing a PR, changing the project to work this way! =)

**Comment by bmeneguele** [comment] 2020-02-20 16:14
@dvinciguerra , nicely done :ok_hand: !
will be waiting your PR :)

**Comment by dvinciguerra** [comment] 2020-02-21 11:51
CC @bmeneguele, @GouveaHeitor

I have worked in some code on this branch...
https://github.com/dvinciguerra/nipe/tree/code-and-command-args-improvements

It's a very early stage code (without tests btw), but can you see the progress and give some impressions or feedback!?

**Comment by GouveaHeitor** [comment] 2020-02-21 14:11
Hi @dvinciguerra,

I took a look at your code and really liked its implementations ...

Feel free to open a PR when you believe it's time!

Just try to stay in sync with our updates on the "develop" branch, there's a lot of new stuff there!

Thx!!

**Comment by dvinciguerra** [comment] 2020-02-21 23:49
I'm merged `develop` branch and now I'm fixing some things. 🤘 

Can I count with you to test this version?
(I don't have a compatible OS ready to test =/)

In the future, I was thinking to write automated tests to make easier change code productively and securely. =)

Thanks dudes! =)

**Comment by bmeneguele** [comment] 2020-02-24 15:22
> Can I count with you to test this version?

Yep, sure. Will take a look on that soon!

> In the future, I was thinking to write automated tests to make easier change code productively and securely. =)

Yees! That's something I'm working on for already existing code/features. We certainly need some unit/integration/regression testing done here :))

Thanks!

**Comment by TheCyberTecky** [comment] 2020-02-25 06:44
Hi folks,

CyberTecky will gladly participate in some testing as well.  As always, everyone’s efforts and time invested in this project is much appreciated!


Chad

Sincerely,

Chad Jordan
Email chad.jordan@outlook.com<mailto:chad.jordan@outlook.com>
-----------------------------------------------------------

**Comment by dvinciguerra** [comment] 2020-03-06 12:41
The PR https://github.com/GouveaHeitor/nipe/pull/99

**Comment by GouveaHeitor** [comment] 2020-05-27 13:09
Resolved.

**Closed** 2020-05-27 13:09 UTC
